# -*- coding: utf-8 -*-
"""YOLOv5 Tutorial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

# Setup

Clone GitHub [repository](https://github.com/ultralytics/yolov5), install [dependencies](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) and check PyTorch and GPU.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

!unzip /content/DeerFinder.v4i.yolov5pytorch.zip

"""# Train"""

!python train.py --img 448 --batch 1 --epochs 200 --data /content/yolov5/data.yaml --weights yolov5s.pt --cache

"""# Validate

"""

!python val.py --weights /content/yolov5/runs/train/exp2/weights/best.pt --data /content/yolov5/data.yaml --img 448 --verbose

"""# Detect

"""

!python detect.py --weights /content/yolov5/runs/train/exp2/weights/best.pt --img 448 --conf 0.25 --source /content/yolov5/test/images